substitutions:
  name: "ultimate-room-sensor"
  friendly_name: "Ultimate Room Sensor"
  project_name: "felipejfc.ultimate-room-sensor"
  project_version: "1.0.1"
  temperature_offset: "0"
  humidity_offset: "0"
  temperature_update_interval: "60s"
  illuminance_update_interval: "5s"
  assist_noise_suppression_level: "1"
  assist_auto_gain: 0dBFS
  assist_volume_multiplier: "15"
  wake_word: hey_jarvis
  log_level: "ERROR"

output:
  - platform: ledc
    pin: GPIO21
    id: led_output
    inverted: True

light:
  - platform: monochromatic
    output: led_output
    id: user_led
light:
  - platform: esp32_rmt_led_strip
    rgb_order: RBG
    pin: GPIO21
    num_leds: 3
    rmt_channel: 2
    chipset: ws2812
    name: "${friendly_name} Status LED"
    id: user_led
    internal: true # Hide from Home Assistant, as it's just an indicator

dashboard_import:
  package_import_url: github://felipejfc/Xiao-Sense_Assist_ESPHome/ultimate-room-sensor.yaml@main
  import_full_config: false

packages:
  device_base: github://felipejfc/Xiao-Sense_Assist_ESPHome/common/xiao-esp32s3-esp-idf-base.yaml@main
  bluetooth_proxy: github://felipejfc/Xiao-Sense_Assist_ESPHome/common/bluetooth-proxy.yaml@main
  pir_sensor: github://felipejfc/Xiao-Sense_Assist_ESPHome/common/pir-sensor.yaml@main
  dht22_sensor: github://felipejfc/Xiao-Sense_Assist_ESPHome/common/dht22-sensor.yaml@main
  tsl2561_sensor: github://felipejfc/Xiao-Sense_Assist_ESPHome/common/tsl2561-sensor.yaml@main
  internal-microphone: github://felipejfc/Xiao-Sense_Assist_ESPHome/common/internal-microphone.yaml@main
  assist_base: github://felipejfc/Xiao-Sense_Assist_ESPHome/common/assist-base.yaml@main
  micro_wake_word: github://felipejfc/Xiao-Sense_Assist_ESPHome/common/micro-wake-word.yaml@main
  display: github://felipejfc/Xiao-Sense_Assist_ESPHome/common/display.yaml@main

#wifi:                      # <-- Uncomment this if you want to manually setup wifi credentials
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password